spring:
  application:
    name: Personal Financial Control - Application Programming Interface
  profiles:
    active: ${ACTIVE_PROFILE:test}

  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    show-sql: true
