spring:
  flyway:
    enabled: true

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/finance}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        ddl-auto: none
        format_sql: true