version: '3.9'

volumes:
  pgdata:
    driver: local

services:
  db:
    image: postgres
    container_name: finance_db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=finance
    volumes:
      - pgdata:/data/postgres
