version: '3.9'

volumes:
  app:
  pgdata:
    driver: local

services:
#  app:
#    build: ../
#    container_name: financial_control_app
#    depends_on:
#      - db
#    environment:
#      DB_URL: jdbc:postgresql://finance_db:5432/finance
#      DB_USERNAME: postgres
#      DB_PASSWORD: postgres
#    ports:
#      - 8081:8080
  db:
    image: postgres
    container_name: finance_db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=finance
    volumes:
      - pgdata:/data/postgres
